import type { AppConfigType, AppLayoutKey, IToast } from "$lib";
import type { ColorMode, ThemeKey } from "@radroots/theme";
import { writable } from "svelte/store";

export const app_layout = writable<AppLayoutKey>(`mobile_base`);
export const app_cfg_type = writable<AppConfigType>(`personal`);
export const app_init = writable<boolean>(false);
export const app_tilt = writable<boolean>(false);
export const app_loading = writable<boolean>(false);
export const app_splash = writable<boolean>(true);
export const app_win = writable<{ h: number, w: number }>({ h: 0, w: 0 });
export const app_notify = writable<string>(``);
export const app_toast = writable<IToast | false>(false);
export const app_blur = writable<boolean>(false);
export const app_db = writable<boolean>(false);
export const app_geoc = writable<boolean>(false);
export const app_thc = writable<ColorMode>(`light`);
export const app_th = writable<ThemeKey>(`os`);
export const app_nostrkey = writable<string>(``);
export const app_nostr_profiles = writable<string[]>([]);
